# Adds systemd presets for Zirconium
kind: manual

sources:
- kind: local
  path: files/systemd-zirconium

build-depends:
- freedesktop-sdk.bst:public-stacks/runtime-gnu.bst

variables:
  strip-binaries: ''

config:
  install-commands:
  - install -Dm644 01-zirconium.preset -t "%{install-root}%{indep-libdir}/systemd/user-preset"
  - install -Dm644 10-zirconium.preset -t "%{install-root}%{indep-libdir}/systemd/system-preset"
  - "%{install-extra}"
