# Partially copied from helix's native languages.toml
[[language]]
name = "yaml"
file-types = [
  "bst",
  "conf",
  "yml",
  "yaml",
  { glob = ".prettierrc" },
  { glob = ".clangd" },
  { glob = ".clang-format" },
  { glob = ".clang-tidy" },
  { glob = ".gem/credentials" },
  { glob = ".kube/config" },
  { glob = ".kube/kuberc" },
  { glob = "yarn.lock" },
  "sublime-syntax",
  "bu",
  { glob = ".stylelintrc" },  # https://stylelint.io/user-guide/configure/
  { glob = ".puppeteerrc" },  # https://pptr.dev/guides/configuration
]
scope = "source.yaml"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "ini"
scope = "source.ini"
file-types = [
  "ini",
  "desktop",
  { glob = "mimeapps.list" },
  # Podman quadlets
  "container",
  "volume",
  "kube",
  "network",
  { glob = "mkosi*.conf" },
  { glob = ".editorconfig" },
  { glob = ".npmrc" },
  { glob = "hgrc" },
  { glob = "npmrc" },
  { glob = "rclone.conf" },
  "properties",
  "cfg",
  "directory"
]
injection-regex = "ini"
comment-token = "#"
indent = { tab-width = 4, unit = " " }
