# Partially copied from helix's native languages.toml
[[language]]
name = "yaml"
file-types = [
  "bst",
  "conf",
  "yml",
  "yaml",
  { glob = ".prettierrc" },
  { glob = ".clangd" },
  { glob = ".clang-format" },
  { glob = ".clang-tidy" },
  { glob = ".gem/credentials" },
  { glob = ".kube/config" },
  { glob = ".kube/kuberc" },
  { glob = "yarn.lock" },
  "sublime-syntax",
  "bu",
  { glob = ".stylelintrc" },  # https://stylelint.io/user-guide/configure/
  { glob = ".puppeteerrc" },  # https://pptr.dev/guides/configuration
]
scope = "source.yaml"
indent = { tab-width = 2, unit = "  " }
