[Output]
SplitArtifacts=uki,partitions
Format=disk

[Content]
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImageFormat=%i_%v_%a
Packages=ddi/zirconium/filesystem.bst
InitrdPackages=ddi/initrd.bst
KernelInitrdModules=default
KernelCommandLine=
    audit=0
    ipe.enforce=0
    mount.usr=dissect
    systemd.image_filter=usr=Zirconium_*:usr-verity=Zirconium_*:usr-verity-sig=Zirconium_*:root=Zirconium-*:swap=Zirconium-*:home=Zirconium-*
    systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
    systemd.verity_usr_options=panic-on-corruption
    rw
    quiet
    splash
