#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  Authors:
#        Chandan Singh <csingh43@bloomberg.net>
#        Tiago Gomes <tiago.gomes@codethink.co.uk>
#        Hec <hec@heccraft.com>

#
# The original "patch" plugin was originally developed in the https://github.com/apache/buildstream/
# repository and was copied from 1a3c707a6c46573ab159de64ac9cd92e7f6027e6
#
# Forked to pull the patch from a remote instead of from a local file
#

"""
remote_patch - apply patches from a url
====================================

**Host dependencies:**

  * patch

**Usage:**

.. code:: yaml

   # Specify the source kind
   kind: remote_patch

   # Optionally specify the strip level, defaults to 1
   strip-level: 1

   # Specify the url of a patch file
   url: upstream:coolpatch.diff

   # Specify the ref. It's a sha256sum of the file you download.
   ref: aa635c93b89fc9d3c013ccdc9c7ce81f604a352fc38596951b666257b5f2e6f2


See `built-in functionality doumentation
<https://docs.buildstream.build/master/buildstream.source.html#core-source-builtins>`_ for
details on common configuration options for sources.


Reporting `SourceInfo <https://docs.buildstream.build/master/buildstream.source.html#buildstream.source.SourceInfo>`_
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The patch source reports the project relative path of the patch file as the *url*.

Further, the patch source reports the `SourceInfoMedium.LOCAL
<https://docs.buildstream.build/master/buildstream.source.html#buildstream.source.SourceInfoMedium.LOCAL>`_
*medium* and the `SourceVersionType.SHA256
<https://docs.buildstream.build/master/buildstream.source.html#buildstream.source.SourceVersionType.SHA256>`_
*version_type*, for which it reports the sha256 checksum of the patch file as the *version*.

The *guess_version* of a patch source is meaningless, as it is tied instead to
the BuildStream project in which it is contained.
"""

import os
from buildstream import DownloadableFileSource, SourceError
from buildstream import utils

#
# Soft import of buildstream symbols only available in newer versions
#
# The BST_MIN_VERSION will provide a better user experience.
#
try:
    from buildstream import SourceInfoMedium, SourceVersionType
except ImportError:
    pass


class RemotePatchSource(DownloadableFileSource):
    # pylint: disable=attribute-defined-outside-init

    BST_MIN_VERSION = "2.5"

    BST_REQUIRES_PREVIOUS_SOURCES_STAGE = True

    def configure(self, node):
        super().configure(node)
        node.validate_keys(["strip-level", *DownloadableFileSource.COMMON_CONFIG_KEYS])
        self.strip_level = node.get_int("strip-level", default=1)
        self.sha256 = None

    def preflight(self):
        # Check if patch is installed, get the binary at the same time
        self.host_patch = utils.get_host_tool("patch")

    def get_unique_key(self):
        # Append the strip level to the unique key generated by DownloadableFileSource
        return super().get_unique_key() + [self.strip_level]

    def stage(self, directory):
        with self.timed_activity("Applying local patch: {}".format(self.url)):

            # Bail out with a comprehensive message if the target directory is empty
            if not os.listdir(directory):
                raise SourceError(
                    "Nothing to patch in directory '{}'".format(directory),
                    reason="patch-no-files",
                )

            strip_level_option = "-p{}".format(self.strip_level)
            self.call(
                [
                    self.host_patch,
                    strip_level_option,
                    "-i",
                    self._get_mirror_file(),
                    "-d",
                    directory,
                ],
                fail="Failed to apply patch {}".format(self.url),
            )

# Plugin entry point
def setup():
    return RemotePatchSource
