# Increase the default vm.max_map_count value
# https://archlinux.org/news/increasing-the-default-vmmax_map_count-value/
# https://bugs.launchpad.net/ubuntu/+source/procps/+bug/2057792
# https://fedoraproject.org/wiki/Changes/IncreaseVmMaxMapCount
vm.max_map_count = 1048576

