name: Build container image

on:
  push:
    branches: [edge]
    paths-ignore: ["**/README.md"]
  pull_request:
    branches: [edge]
  workflow_dispatch:
    inputs:
      skip-base:
        description: Skip building Hawaii image
        default: false
        type: boolean
      skip-jackrabbit:
        description: Skip building Hawaii Jackrabbit image
        default: false
        type: boolean
      pull-before-configure:
        description: "Pull from cache before build"
        type: boolean
        default: false
      disable-remote-execution:
        description: "Don't configure remote-execution server (requires valid CASD keys)"
        type: boolean
        default: false

env:
  IMAGE_DESC: "Opinionated niri + bootc image"
  IMAGE_KEYWORDS: "bootc,niri,freedesktop-sdk"
  IMAGE_LOGO_URL: "https://avatars.githubusercontent.com/u/237492973?s=400&v=4"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "edge"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-hawaii:
    name: Build Hawaii Bootc Image
    if: |
      github.event.inputs.skip-base == 'false' || !github.event.inputs.skip-base
    uses: ./.github/workflows/reusable-build-bootc.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image-name: "zirconium-hawaii"
      element: "oci/zirconium/image.bst"
      default-tag: "edge"
      disable-remote-execution: ${{ inputs.disable-remote-execution == true }}
      publish: ${{ github.event_name != 'pull_request' && github.ref == format('refs/heads/edge', github.event.repository.default_branch) }}
      pull-before-configure: ${{ inputs.pull-before-configure == true }}

  # Run this build AFTER build-hawaii. build-hawaii will cache all of the base packages.
  build-hawaii-jackrabbit:
    name: Build Hawaii Jackrabbit Bootc Image
    if: |
      !failure() && !cancelled() &&
      (github.event.inputs.skip-jackrabbit == 'false' || !github.event.inputs.skip-jackrabbit)
    uses: ./.github/workflows/reusable-build-bootc.yml
    needs: build-hawaii
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image-name: "zirconium-hawaii-jackrabbit"
      element: "oci/jackrabbit/image.bst"
      default-tag: "edge"
      disable-remote-execution: ${{ inputs.disable-remote-execution == true }}
      publish: ${{ github.event_name != 'pull_request' && github.ref == format('refs/heads/edge', github.event.repository.default_branch) }}
      pull-before-configure: ${{ inputs.pull-before-configure == true }}
