---
name: "Build Bootc Image"
on:
  workflow_call:
    inputs:
      image-name:
        description: "The name of the image to build"
        required: true
        type: string
      default-tag:
        description: "Default tag to push to"
        required: false
        type: string
        default: "latest"
      publish:
        description: "Publish this image"
        required: false
        type: boolean
        default: true
      element:
        description: "Dependency element to build"
        required: true
        type: string
      image-element:
        description: "Image element to build"
        required: true
        type: string
      pull-before-configure:
        description: "Pull from cache before build"
        type: boolean
        default: false
      remote-execution:
        description: "Configure remote-execution server (requires valid CASD keys)"
        type: boolean
        # default: true
        default: false
    secrets:
      SIGNING_SECRET:
        description: "The private key used to sign the image"
        required: false

env:
  IMAGE_DESC: "Opinionated niri + bootc image"
  IMAGE_KEYWORDS: "bootc,niri,freedesktop-sdk"
  IMAGE_LOGO_URL: "https://avatars.githubusercontent.com/u/237492973?s=400&v=4"
  IMAGE_NAME: "${{ inputs.image-name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "${{ inputs.default-tag }}"

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-24.04
    timeout-minutes: 600 # 10 hours
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - name: Set Image version
        run: |
          just generate-image-version

      - name: Pull artifacts and sources
        if: inputs.pull-before-configure
        run: |
          just bst artifact pull --deps all ${{ inputs.element }}

      - name: Configure BuildStream
        env:
          CASD_CLIENT_CERT: ${{ vars.CASD_CLIENT_CERT }}
          CASD_CLIENT_KEY: ${{ secrets.CASD_CLIENT_KEY }}
          REMOTE_EXECUTION: ${{ inputs.remote-execution }}
        run: |
          mkdir -p ~/.config
          if [[ -n "$CASD_CLIENT_CERT" ]] && [[ -n "$CASD_CLIENT_KEY" ]]; then
            # Setup certificate for pushing to the cache
            mkdir -p ~/.config/hawaii
            echo "$CASD_CLIENT_CERT" > ~/.config/hawaii/client.crt
            echo "$CASD_CLIENT_KEY" >  ~/.config/hawaii/client.key

          cat > ~/.config/buildstream.conf << EOF
          # BuildStream user configuration
          scheduler:
            fetchers: 24
            builders: 4
            network-retries: 3

          logging:
            verbose: true
            message-format: '[%{wallclock}][%{elapsed}][%{key}][%{element}] %{action} %{message}'
            error-lines: 80

          artifacts:
            servers:
            - url: https://cache.projectbluefin.io:11002
              push: true
              connection-config:
                keepalive-time: 60
                retry-limit: 5
                retry-delay: 1000
                request-timeout: 180
              auth:
                client-key: ~/.config/hawaii/client.key
                client-cert: ~/.config/hawaii/client.crt

          source-caches:
            servers:
            - url: https://cache.projectbluefin.io:11002
              push: true
              connection-config:
                keepalive-time: 60
                retry-limit: 5
                retry-delay: 1000
                request-timeout: 180
              auth:
                client-key: ~/.config/hawaii/client.key
                client-cert: ~/.config/hawaii/client.crt

          EOF
          if [ "${REMOTE_EXECUTION}" = "true" ]; then
          cat >> ~/.config/buildstream.conf << EOF
          cache:
            storage-service:
              url: https://cache.projectbluefin.io:11002
              connection-config:
                keepalive-time: 60
                retry-limit: 5
                retry-delay: 1000
                request-timeout: 180
              auth:
                client-key: ~/.config/hawaii/client.key
                client-cert: ~/.config/hawaii/client.crt

          remote-execution:
            execution-service:
              url: https://cache.projectbluefin.io:11002
              connection-config:
                keepalive-time: 60
                retry-limit: 5
                retry-delay: 1000
                request-timeout: 180
              auth:
                client-key: ~/.config/hawaii/client.key
                client-cert: ~/.config/hawaii/client.crt
            action-cache-service:
              url: https://cache.projectbluefin.io:11002
              connection-config:
                keepalive-time: 60
                retry-limit: 5
                retry-delay: 1000
                request-timeout: 180
              auth:
                client-key: ~/.config/hawaii/client.key
                client-cert: ~/.config/hawaii/client.crt
          build:
            max-jobs: 12
            retry-failed: true
          EOF

          else

          cat >> ~/.config/buildstream.conf << EOF
          build:
            retry-failed: true
          EOF
          fi

          else
          # if there's no CASD keys, don't configure any servers in buildstream.conf
          cat > ~/.config/buildstream.conf << EOF
          # BuildStream user configuration
          scheduler:
            fetchers: 24
            builders: 4
            network-retries: 3

          logging:
            verbose: true
            message-format: '[%{wallclock}][%{elapsed}][%{key}][%{element}] %{action} %{message}'
            error-lines: 80

          build:
            retry-failed: true
          EOF
          fi

      - name: Print BuildStream configuration
        run: |
          cat ~/.config/buildstream.conf

      # This generates a timestamp like what is defined on the ArtifactHub documentation
      # E.G: 2022-02-08T15:38:15Z'
      # https://artifacthub.io/docs/topics/repositories/container-images/
      # https://linux.die.net/man/1/date
      - name: Get current date
        id: date
        run: echo "date=$(date -u +%Y\-%m\-%d\T%H\:%M\:%S\Z)" | tee "${GITHUB_OUTPUT}"

      - name: Get buildstream metadata
        id: bstmetadata
        run: |
          set -xeuo pipefail
          version="$(yq .image-version include/image-version.yml)"

          echo "version=${version#*$'.'}" >> "${GITHUB_OUTPUT}"
          echo "branch=$(yq .variables.branch project.conf)" >> "${GITHUB_OUTPUT}"

      - name: Image Metadata
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        id: metadata
        with:
          tags: |
            type=raw,value=${{ env.DEFAULT_TAG }},enable=${{ env.DEFAULT_TAG == 'latest' }}
            type=raw,value=${{ steps.bstmetadata.outputs.branch }}
            type=raw,value=${{ env.DEFAULT_TAG }}.${{ steps.bstmetadata.outputs.version }},enable=${{ env.DEFAULT_TAG == 'latest' }}
            type=raw,value=${{ steps.bstmetadata.outputs.branch }}.${{ steps.bstmetadata.outputs.version }}
            type=ref,event=pr
            type=sha,enable=${{ github.event_name == 'pull_request' }}
          labels: |
            containers.bootc=1
            io.artifacthub.package.deprecated=false
            io.artifacthub.package.keywords=${{ env.IMAGE_KEYWORDS }}
            io.artifacthub.package.license=MIT
            io.artifacthub.package.logo-url=${{ env.IMAGE_LOGO_URL }}
            io.artifacthub.package.prerelease=false
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/${{ github.sha }}/README.md
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
            org.opencontainers.image.documentation=https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/${{ github.sha }}/README.md
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/blob/${{ github.sha }}/Containerfile
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/tree/${{ github.sha }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ steps.bstmetadata.outputs.branch }}.${{ steps.bstmetadata.outputs.version }}
          sep-tags: " "
          sep-annotations: " "

      - name: Free disk space
        uses: hastd/free-disk-space@68572aeaadb7f76bd408246328e95926323402b5 # v0.1.2

      - name: Enable unprivileged userns
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Print disk usage before image build
        run: |
          df -h

      - name: Buildstream build (dependencies)
        run: |
          just bst build ${{ inputs.element }}

      # Delete casd token 
      - name: Delete token
        if: always()
        run: rm -f ~/.config/hawaii/client.key

      # For some reason, it takes about 5-6x longer to build filesystem and runtime when pushing.
      # Here, we ensure that we don't use the remote-execution server for the specific elements that are slower to build.
      - name: Configure BuildStream to not push or use remote-execution server
        run: |
          cat > ~/.config/buildstream.conf << EOF
          # BuildStream user configuration
          scheduler:
            fetchers: 24
            builders: 4
            network-retries: 3

          logging:
            verbose: true
            message-format: '[%{wallclock}][%{elapsed}][%{key}][%{element}] %{action} %{message}'
            error-lines: 80

          build:
            retry-failed: true
          EOF

      - name: Buildstream build (image)
        run: |
          just bst build ${{ inputs.image-element }}

      - name: Print disk usage after image build
        run: |
          df -h

      - name: Export Initial OCI Image
        if: inputs.publish
        run: |
          just bst artifact checkout --tar - ${{ inputs.image-element }} | podman load

      - name: Build final OCI Image
        if: inputs.publish
        env:
          LABELS: ${{ steps.metadata.outputs.labels }}
          TAGS: ${{ steps.metadata.outputs.tags }}
        run: |
          set -x

          BUILD_ARGS=("--squash-all")
          for tag in $TAGS; do
            BUILD_ARGS+=("--tag" "$IMAGE_REGISTRY/$IMAGE_NAME:$tag")
          done

          while IFS= read -r label; do
            BUILD_ARGS+=("--label" "$label")
            BUILD_ARGS+=("--annotation" "$label")
          done <<< "$LABELS"

          podman build "${BUILD_ARGS[@]}" .

      - name: Login to GitHub Container Registry
        if: inputs.publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOGIN_USER: ${{ github.actor }}
        run: |
          echo "${GITHUB_TOKEN}" | podman login -u "${LOGIN_USER}" --password-stdin "ghcr.io"
          echo "${GITHUB_TOKEN}" | docker login -u "${LOGIN_USER}" --password-stdin "ghcr.io" # For cosign

      - name: Push to GHCR
        if: inputs.publish
        id: push
        env:
          TAGS: ${{ steps.metadata.outputs.tags }}
          MAX_RETRIES: 3
        run: |
          set -x
          for i in $(seq "${MAX_RETRIES}"); do
            for TAG in $TAGS; do
              podman push --compression-format=zstd "${IMAGE_REGISTRY}/${IMAGE_NAME}:$TAG" || sleep $((5 * i))
            done
          done

      - name: Install Cosign
        if: inputs.publish
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Sign Image
        if: inputs.publish
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        run: |
          for tag in ${{ steps.metadata.outputs.tags }}; do
            cosign sign -y --new-bundle-format=false --use-signing-config=false --key env://COSIGN_PRIVATE_KEY "${IMAGE_REGISTRY}/${IMAGE_NAME}:$tag"
          done
